### ISSUE TITLE
Failing tests on master, worried flakybot is not configured

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/python-websecurityscanner#35]
Looking at #34, it looks like tests are failing on master.  That in and of itself is a problem, but I'm far more concerned that flakybot isn't configured properly or doing it's thing.

**Comment by busunkim96** [comment]
Yep you're correct, flakybot is only configured on the samples tests so it won't catch anything that breaks elsewhere.

**Comment by JustinBeckwith** [comment]
Interesting!  Which specific tests are breaking here?  System?  Unit?  Is it common for those to be persistently broken without the samples tests being broken?

The spirit of what I'm trying to get at here - if master is red, and we're blocked - I would like an automatic tracking issue to be filed so we know about it.  We're chasing way too many repos to deal with whack-a-repo when they go red.

**Comment by busunkim96** [comment]
This was addressed in https://github.com/googleapis/synthtool/pull/950 and the change will eventually trickle through here in a template PR.
